use_frameworks!

platform :ios, '10.0'

target 'TeneasyChatSDK_iOS_Example' do
  pod 'TeneasyChatSDK_iOS', :path => '../'
  #pod 'TeneasyChatSDK_iOS', :git => 'https://github.com/tianxuefeng/TeneasyChatSDK_iOS.git'
  target 'TeneasyChatSDK_iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #pod 'Starscream', '~> 4.0.0'
  end
  

  
end
