use_frameworks!

platform :ios, '10.0'

target 'TeneasyChatSDK_iOS_Example' do
  pod 'TeneasyChatSDK_iOS', :path => '../'
  pod 'SwiftDate', '~> 6.3.1'
  #pod 'SwiftProtobuf', '~> 1.20.3'
  #pod 'TeneasyChatSDK_iOS', :git => 'https://github.com/tianxuefeng/TeneasyChatSDK_iOS.git'
  target 'TeneasyChatSDK_iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  
  end
  

  
end
