use_frameworks!

platform :ios, '10.0'

target 'TeneasyChatSDK_iOS_Example' do
  pod 'TeneasyChatSDK_iOS', :path => '../'

  target 'TeneasyChatSDK_iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
